# Site settings
title: Manash Pratim
description: "An undergraduate student at IIT Kharagpur pursuing research in robotics. Experience in aerial robots, perception, planning and computer vision."
meta_tags: "manash, pratim, iit, kharagpur, aerial robotics, robotics, computer vision"

url: "http://manashpratim.com"
author:
  name: "Manash Pratim Das"
  email: "mpdmanash@iitkgp.ac.in"
  url: "http://manashpratim.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
highlighter: rouge
source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

google_analytics: ''

# Options
custom_header: false
custom_nav_footer: false
reverse: false

#social-icons
facebook: mpdmanash
twitter: manashraja
instagram: captainmpd
linkedin: manshpratim
github: manashraja
email: mpdmanash@iitkgp.ac.in
scholar: ze5yAzkAAAAJ&hl

# Details for the RSS feed generator
url:            'http://manashpratim.com'
author:         'Manash Pratim'
authorTwitter:  'manashraja'